# Generated by Django 3.2 on 2021-04-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('rg', models.IntegerField(unique=True)),
                ('cpf', models.IntegerField(unique=True)),
                ('dn', models.DateTimeField()),
                ('sexo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Tikal.cliente')),
                ('ddd', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Telefone',
            },
            bases=('Tikal.cliente',),
        ),
    ]
